#!/usr/bin/env bash
# Check objective: Publish only the pinned Kyverno CLI with passing scans and verified signatures from main.
set -euo pipefail
umask 077
unset KYVERNO_RISK_DECISION
die(){ printf '%s\n' "$1" >&2; exit 65; }
need(){ command -v "$1" >/dev/null 2>&1 || die "missing command: $1"; }
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"; cd "$root"
[ "${GITHUB_REF:-}" = refs/heads/main ] && [ "${GITHUB_REPOSITORY:-}" = s1ns3nz0/node-operator ] || die 'publication is restricted to repository main'
[[ "${GITHUB_SHA:-}" =~ ^[a-f0-9]{40}$ && "${GITHUB_RUN_ID:-}" =~ ^[1-9][0-9]*$ && "${GITHUB_RUN_ATTEMPT:-}" =~ ^[0-9]+$ && "${ACCOUNT_ID:-}" =~ ^[0-9]{12}$ && "${AWS_REGION:-}" =~ ^ap-northeast-[12]$ && "${AWS_ROLE_ARN:-}" =~ ^arn:aws:iam::${ACCOUNT_ID}:role/.+$ ]] || die 'release context is invalid'
[ "${DEPLOYMENT_NAME:-}" = node-operator ] || die 'Kyverno CLI publication must target canonical node-operator GitOps repository'
[ "$(git rev-parse HEAD)" = "$GITHUB_SHA" ] || die 'checkout differs from selected revision'
[[ "${RUNNER_TEMP:-}" = /* && -d "$RUNNER_TEMP" && "${ACTIONS_ID_TOKEN_REQUEST_URL:-}" = https://* && -n "${ACTIONS_ID_TOKEN_REQUEST_TOKEN:-}" ]] || die 'OIDC context is invalid'
inputs=(.ci/kyverno-cli/Dockerfile .ci/kyverno-cli/source-lock.json .ci/kyverno-cli/scripts/update-etcd.sh .ci/kyverno-cli/risk-acceptance.json scripts/release/kyverno_cli_publication_record.py scripts/release/publish-kyverno-cli-image.sh scripts/ci/scan-release-sbom.sh scripts/ci/verify-release-scan-attestation.sh scripts/ci/assess-kyverno-cli-risk-acceptance.py scripts/ci/install-validator-signing-fence-release-tools.sh .github/workflows/image-publish.yml)
for input in "${inputs[@]}"; do [ -f "$input" ] && [ ! -L "$input" ] || die 'reviewed input is unavailable'; done
if ! git ls-files --error-unmatch -- "${inputs[@]}" >/dev/null || ! git diff --quiet HEAD -- "${inputs[@]}" || ! git diff --cached --quiet -- "${inputs[@]}"; then die 'publisher inputs differ from selected revision'; fi
for command in aws curl docker jq python3 git; do need "$command"; done
# Refuse contradictory source claims before building or obtaining AWS credentials.
PYTHONPATH=scripts/release python3 -c 'from pathlib import Path; from kyverno_cli_publication_record import source; source(Path("."))'
record_dir="$RUNNER_TEMP/kyverno-cli-publication-records"; [ ! -e "$record_dir" ] && [ ! -L "$record_dir" ] || die 'record output already exists'; mkdir -m 700 "$record_dir"
tools="$RUNNER_TEMP/kyverno-cli-tools"; scripts/ci/install-validator-signing-fence-release-tools.sh "$tools"; export PATH="$tools:$PATH"; need syft; need grype; need cosign
scratch="$(mktemp -d "$RUNNER_TEMP/.kyverno-cli-release.XXXXXX")"
cleanup(){ unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN DOCKER_CONFIG; rm -rf "$scratch"; }; trap cleanup EXIT
# Retain only non-secret scan/signature artifacts even when a gate rejects the image.
evidence="$record_dir/evidence"; mkdir -m 700 "$evidence"; docker_config="$scratch/docker-config"; mkdir -m 700 "$docker_config"; export DOCKER_CONFIG="$docker_config"
token_file="$scratch/oidc-token"; credentials="$scratch/aws.json"; curl_config="$scratch/curl.conf"; oidc_response="$scratch/oidc.json"
repository=node-operator-baseline-gitops-nodes; registry="$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"; tag="kyverno-cli-$GITHUB_SHA-$GITHUB_RUN_ID-$GITHUB_RUN_ATTEMPT"; destination="$registry/$repository:$tag"; local_image="$repository:local-$GITHUB_SHA-$GITHUB_RUN_ID"
docker build --pull=false --platform linux/amd64 -f .ci/kyverno-cli/Dockerfile -t "$local_image" .ci/kyverno-cli
[ "$(docker image inspect --format '{{.Os}}/{{.Architecture}}' "$local_image")" = linux/amd64 ] || die 'CLI image is not linux/amd64'
printf 'header = "Authorization: bearer %s"\n' "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" > "$curl_config"; curl --fail --silent --show-error --connect-timeout 10 --max-time 30 --config "$curl_config" --output "$oidc_response" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com"; jq -er .value "$oidc_response" > "$token_file"
aws sts assume-role-with-web-identity --role-arn "$AWS_ROLE_ARN" --role-session-name "kyverno-cli-$GITHUB_RUN_ID" --web-identity-token "file://$token_file" --duration-seconds 900 --cli-connect-timeout 10 --cli-read-timeout 20 > "$credentials"
AWS_ACCESS_KEY_ID="$(jq -er .Credentials.AccessKeyId "$credentials")"
AWS_SECRET_ACCESS_KEY="$(jq -er .Credentials.SecretAccessKey "$credentials")"
AWS_SESSION_TOKEN="$(jq -er .Credentials.SessionToken "$credentials")"
export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
printf '::add-mask::%s\n' "$AWS_ACCESS_KEY_ID" "$AWS_SECRET_ACCESS_KEY" "$AWS_SESSION_TOKEN"; role_name="${AWS_ROLE_ARN##*/}"; identity="$(aws sts get-caller-identity --output json)"; [ "$(jq -er .Account <<<"$identity")" = "$ACCOUNT_ID" ] && [[ "$(jq -er .Arn <<<"$identity")" == "arn:aws:sts::$ACCOUNT_ID:assumed-role/$role_name/"* ]] || die 'assumed identity differs'
aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$registry"; docker tag "$local_image" "$destination"; docker push "$destination"
detail="$(aws ecr describe-images --registry-id "$ACCOUNT_ID" --region "$AWS_REGION" --repository-name "$repository" --image-ids "imageTag=$tag" --output json)"; digest="$(jq -er --arg account "$ACCOUNT_ID" --arg repo "$repository" '.imageDetails|select(type=="array" and length==1)|.[0]|select(.registryId==$account and .repositoryName==$repo)|.imageDigest|select(test("^sha256:[a-f0-9]{64}$"))' <<<"$detail")"; subject="${destination%:*}@$digest"
SYFT_CHECK_FOR_APP_UPDATE=false syft scan "registry:$subject" --source-name "$repository" --source-version "$digest" --output "cyclonedx-json=$evidence/sbom.json"; GRYPE_CHECK_FOR_APP_UPDATE=false grype "sbom:$evidence/sbom.json" --output json --file "$evidence/grype.json"; scripts/ci/scan-release-sbom.sh "$evidence/sbom.json" "$evidence/scan.json"; jq -e --arg digest "$digest" '.metadata.component.version==$digest' "$evidence/sbom.json" >/dev/null
jq '{status,findings}' "$evidence/scan.json"
identity_name='https://github.com/s1ns3nz0/node-operator/.github/workflows/image-publish.yml@refs/heads/main'; issuer='https://token.actions.githubusercontent.com'; scan_type='https://github.com/s1ns3nz0/node-operator/attestations/scan-summary/v1'
source_commit="$(jq -er '.source.commit | select(test("^[a-f0-9]{40}$"))' .ci/kyverno-cli/source-lock.json)"; input_sha="$(PYTHONPATH=scripts/release python3 -c 'from pathlib import Path; from kyverno_cli_publication_record import input_sha256; print(input_sha256(Path(".")))')"
if jq -e '.status=="passed" and .findings.critical==0 and .findings.high==0 and .findings.unknown==0' "$evidence/scan.json" >/dev/null; then risk_arg=(); else python3 scripts/ci/assess-kyverno-cli-risk-acceptance.py "$root" "$evidence" "$input_sha" > "$evidence/risk-decision.json"; python3 scripts/ci/assess-kyverno-cli-risk-acceptance.py "$root" "$evidence" "$input_sha" --verify "$evidence/risk-decision.json" >/dev/null; jq -e --slurpfile decision "$evidence/risk-decision.json" '.findings == $decision[0].raw_scan_summary.findings' "$evidence/scan.json" >/dev/null; jq -e '.status=="accepted-with-residual-risk"' "$evidence/risk-decision.json" >/dev/null; risk_arg=(--risk-decision "$evidence/risk-decision.json"); fi
jq -n --arg revision "$GITHUB_SHA" --arg source_commit "$source_commit" --arg input "$input_sha" --arg run "$GITHUB_RUN_ID" '{buildDefinition:{buildType:"https://slsa.dev/container-based-build/v1",externalParameters:{kyverno_cli_input_sha256:$input},resolvedDependencies:[{uri:"git+https://github.com/s1ns3nz0/node-operator",digest:{gitCommit:$revision}},{uri:"git+https://github.com/kyverno/kyverno",digest:{gitCommit:$source_commit}}]},runDetails:{builder:{id:"https://github.com/Attestations/GitHubHostedActions@v1"},metadata:{invocationId:$run}}}' > "$evidence/provenance.json"
# Pinned Cosign v3 writes independent OCI referrers, not mutable legacy .att tags.
cosign sign --yes --new-bundle-format=true "$subject"
cosign attest --yes --new-bundle-format=true --type slsaprovenance1 --predicate "$evidence/provenance.json" "$subject"
cosign attest --yes --new-bundle-format=true --type cyclonedx --predicate "$evidence/sbom.json" "$subject"
if [ "${#risk_arg[@]}" -eq 0 ]; then cosign attest --yes --new-bundle-format=true --type "$scan_type" --predicate "$evidence/scan.json" "$subject"; else raw_scan_type='https://github.com/s1ns3nz0/node-operator/attestations/kyverno-cli-raw-grype/v1'; risk_type='https://github.com/s1ns3nz0/node-operator/attestations/kyverno-cli-risk-decision/v1'; cosign attest --yes --new-bundle-format=true --type "$raw_scan_type" --predicate "$evidence/grype.json" "$subject"; cosign attest --yes --new-bundle-format=true --type "$risk_type" --predicate "$evidence/risk-decision.json" "$subject"; fi
cosign verify --certificate-identity "$identity_name" --certificate-oidc-issuer "$issuer" --certificate-github-workflow-sha "$GITHUB_SHA" "$subject" > "$evidence/signature.json"; cosign verify-attestation --type slsaprovenance1 --certificate-identity "$identity_name" --certificate-oidc-issuer "$issuer" --certificate-github-workflow-sha "$GITHUB_SHA" "$subject" > "$evidence/provenance-verified.json"; cosign verify-attestation --type cyclonedx --certificate-identity "$identity_name" --certificate-oidc-issuer "$issuer" --certificate-github-workflow-sha "$GITHUB_SHA" "$subject" > "$evidence/sbom-verified.json"
if [ "${#risk_arg[@]}" -eq 0 ]; then cosign verify-attestation --type "$scan_type" --certificate-identity "$identity_name" --certificate-oidc-issuer "$issuer" --certificate-github-workflow-sha "$GITHUB_SHA" "$subject" > "$evidence/scan-verified.json"; scripts/ci/verify-release-scan-attestation.sh "$evidence/scan-verified.json" "$digest" "$evidence/scan.json"; else cosign verify-attestation --type "$raw_scan_type" --certificate-identity "$identity_name" --certificate-oidc-issuer "$issuer" --certificate-github-workflow-sha "$GITHUB_SHA" "$subject" > "$evidence/raw-grype-verified.json"; cosign verify-attestation --type "$risk_type" --certificate-identity "$identity_name" --certificate-oidc-issuer "$issuer" --certificate-github-workflow-sha "$GITHUB_SHA" "$subject" > "$evidence/risk-decision-verified.json"; jq -s -e --arg digest "${digest#sha256:}" --arg type "$raw_scan_type" --slurpfile raw "$evidence/grype.json" 'def s: if length==1 and (.[0]|type)=="array" then .[0] else . end|map(.payload|@base64d|fromjson); s|any(.[]; (._type=="https://in-toto.io/Statement/v0.1" or ._type=="https://in-toto.io/Statement/v1") and .predicateType==$type and (.subject|any(.digest.sha256==$digest)) and .predicate==$raw[0])' "$evidence/raw-grype-verified.json" >/dev/null; jq -s -e --arg digest "${digest#sha256:}" --arg type "$risk_type" --slurpfile decision "$evidence/risk-decision.json" 'def s: if length==1 and (.[0]|type)=="array" then .[0] else . end|map(.payload|@base64d|fromjson); s|any(.[]; (._type=="https://in-toto.io/Statement/v0.1" or ._type=="https://in-toto.io/Statement/v1") and .predicateType==$type and (.subject|any(.digest.sha256==$digest)) and .predicate==$decision[0])' "$evidence/risk-decision-verified.json" >/dev/null; export KYVERNO_RISK_DECISION="$evidence/risk-decision.json"; fi
PYTHONPATH="$root/scripts/release" python3 - "$root" "$record_dir/kyverno-cli-publication-record.json" "$GITHUB_SHA" "$subject" "$digest" "$GITHUB_RUN_ID" <<'PY'
import json, os, sys
from pathlib import Path
from kyverno_cli_publication_record import create_record
root, output, revision, image, digest, run = sys.argv[1:]; decision=os.environ.get("KYVERNO_RISK_DECISION"); value=create_record(Path(root), release_revision=revision, image_ref=image, manifest_digest=digest, run_id=run, risk_decision=Path(decision) if decision else None)
fd=os.open(output, os.O_WRONLY|os.O_CREAT|os.O_EXCL, 0o600)
with os.fdopen(fd,"w") as handle: json.dump(value,handle,sort_keys=True,separators=(",",":")); handle.write("\n"); handle.flush(); os.fsync(handle.fileno())
PY
printf 'private_image=%s\nsource_revision=%s\nrelease_verification=PASS\n' "$subject" "$GITHUB_SHA" >> "${GITHUB_STEP_SUMMARY:-/dev/null}"
