apiVersion: v1
kind: Service
metadata:
  name: nethermind-execution
  namespace: node-operator
  labels:
    app.kubernetes.io/name: nethermind
    app.kubernetes.io/component: execution-client
    app.kubernetes.io/part-of: hoodi-node
spec:
  clusterIP: None
  publishNotReadyAddresses: false
  selector:
    app.kubernetes.io/name: nethermind
    app.kubernetes.io/component: execution-client
    app.kubernetes.io/part-of: hoodi-node
  ports:
    - name: p2p-tcp
      port: 30303
      protocol: TCP
      targetPort: p2p-tcp
    - name: p2p-udp
      port: 30303
      protocol: UDP
      targetPort: p2p-udp
