# The installer supplies this body only after it has selected a validator set
# and rendered the reviewed local dashboard document. Null is intentional: it
# prevents this Terraform module from inventing a validator-set default or
# creating a dashboard before that delivery input exists.
variable "validator_monitoring_dashboard_body" {
  description = "Optional JSON body generated by validator_monitoring_dashboard.py. The installer must supply it before validator monitoring is complete."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition = var.validator_monitoring_dashboard_body == null ? true : try(
      startswith(jsonencode(jsondecode(var.validator_monitoring_dashboard_body).widgets), "[") &&
      length(jsondecode(var.validator_monitoring_dashboard_body).widgets) > 0,
      false,
    )
    error_message = "validator_monitoring_dashboard_body must be null or JSON with a non-empty widgets array."
  }
}

resource "aws_cloudwatch_dashboard" "validator" {
  count = var.validator_monitoring_dashboard_body == null ? 0 : 1

  dashboard_name = "${var.name}-validator"
  dashboard_body = var.validator_monitoring_dashboard_body

  lifecycle {
    # Metric and Logs widgets are regional. Reject a body rendered for another
    # region instead of silently creating a dashboard with cross-region data.
    precondition {
      condition = alltrue([
        for widget in jsondecode(var.validator_monitoring_dashboard_body).widgets :
        !contains(["metric", "log"], try(widget.type, "")) ||
        try(widget.properties.region, "") == var.aws_region
      ])
      error_message = "Every metric and log widget in validator_monitoring_dashboard_body must use var.aws_region."
    }
  }
}

output "validator_monitoring_dashboard_name" {
  description = "CloudWatch dashboard name when the installer supplied a rendered body; null otherwise."
  value       = try(aws_cloudwatch_dashboard.validator[0].dashboard_name, null)
}
