apiVersion: v1
kind: ServiceAccount
metadata:
  name: nethermind-execution
  namespace: node-operator
  labels:
    app.kubernetes.io/name: nethermind
    app.kubernetes.io/component: execution-client
    app.kubernetes.io/part-of: hoodi-node
automountServiceAccountToken: false
