apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: validator-log-collector-metadata
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: validator-log-collector-metadata
subjects:
  - kind: ServiceAccount
    name: validator-log-collector
    namespace: validator-observability
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: validator-log-collector-metadata
